version: '3'
services:
    web:
        build:
            context: backend
        command: 'bash -c "gunicorn --bind 0.0.0.0:40004 --workers=2 --timeout 600 --log-level debug --reload ninja.wsgi:application"'
        container_name: django_app
        ports:
            - '40004:40004'
        # networks:
        #     static-network:
        #         ipv4_address: 172.16.0.4
    broker:
        container_name: redis_container
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        expose:
            - '6379'
    rabbitmq:
        image: 'rabbitmq:3.6-management-alpine'
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
    frontend:
        build: ninja-frontend
        hostname: ninja.cbre.com
        container_name: ninja.cbre.com
        restart: always
        ports:
            - '8082:80'
        # networks:
        #     static-network:
        #         ipv4_address: 172.16.0.5
    celery:
        build:
            context: backend
        command: 'bash -c "celery worker -A ninja -Q ''ninja_queue'' --loglevel=INFO"'
        container_name: celery_worker
    mongo:
        image: 'mongo'
        container_name: 'mongo_container'
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - '27017-27019:27017-27019'
# networks:
#     static-network:
#         ipam:
#             driver: default
#             config:
#                 -subnet: 172.16.0.0/16
